### PR TITLE
[IMP] add apps site description for carrier gls

### PR DESCRIPTION
**Pull request by bealdav**
To have a good display on https://www.odoo.com/apps

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please use OCA template for this purpose: https://github.com/OCA/maintainers-tools/blob/master/template/module/static/description/index.html

**Comment by bealdav** [comment]
OCA template is for v8, in v7 description is different

**Comment by pedrobaeza** [comment]
I think for HTML description can be used the same, isn't it?

**Comment by bealdav** [comment]
Have you got an example of a module with this template displayed correctly in apps ? 
If I can see one, I'll update my page.
Thanks

**Comment by pedrobaeza** [comment]
No, not yet, but it's a good moment to try :wink:

**Comment by Viggor** [comment]
Despite there is no unified system between description in Odoo system and Odoo apps (I could be wrong) I give a :+1: . The travis fail is not caused by this modification.

**Comment by yvaucher** [comment]
For v8.0 it definitely will need to follow OCA template. I have no strong opinion about v7.0 html though as most of 7.0 modules' readme are not following OCA template
:+1:

**Pull request merged**
