### PR TITLE
[16.0][IMP] delivery_deliverea: add exchange attribute in serviceAttributes 

### PR DESCRIPTION
**Pull request by imoralesc**
Add exchange service attribute in _get_service_attributes method. 

Selección_245

### CODE REVIEW

**Review by OscarIndias — APPROVED** [review]
LGTM

**Comment by imoralesc** [comment]
Hi @pedrobaeza, could you check this PR?

**Comment by pedrobaeza** [comment]
Please use a proper commit message:

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message

**Comment by imoralesc** [comment]
> Please use a proper commit message:
> 
> https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message

Done :wink: @pedrobaeza

**Comment by pedrobaeza** [comment]
`[UPD]` is not a valid tag. You have `[IMP]` or `[FIX]`.

**Comment by imoralesc** [comment]
> `[UPD]` is not a valid tag. You have `[IMP]` or `[FIX]`.

Done @pedrobaeza

**Review by pedrobaeza — COMMENTED** [review]
Is this something reasonable to be put at carrier level? Shouldn't it be at picking level?

**Comment by imoralesc** [comment]
> Is this something reasonable to be put at carrier level? Shouldn't it be at picking level?

Hi @pedrobaeza, it must be at carrier level because it is a shipment where the carrier delivers one parcel and collects another at the time of delivery.

**Comment by pedrobaeza** [comment]
shipment = picking, so that's why I say it. If not, you are force to have 2 carriers for the same shipper.

**Comment by imoralesc** [comment]
@pedrobaeza it is mandatory to configure it as two carriers, they are completely different operations.

The customer uses that type of transport for a specific case, and also this attribute depends on the carrier. Not all carriers are compatible with this attribute, in other carriers it is a simple service.

**Comment by pedrobaeza** [comment]
> The customer uses that type of transport for a specific case

Yes, and for that case, you can mark the check instead of selecting the other carrier.

> and also this attribute depends on the carrier.

Not sure about this affirmation. In the image screenshot, the text says "Mark expedition as exchange", so it seems an attribute per expedition, not per carrier or service.

> Not all carriers are compatible with this attribute

Correct, but this can work the same as others attribute that declares if they are capable or not.

**Pull request closed without merging**
