### PR TITLE
[14.0][MIG] delivery_auto_refresh: Migration to 14.0

### PR DESCRIPTION
**Pull request by yankinmax**
Here what has changed:
- [ ] `action_done` on 'stock.picking' become `_action_done`
- [ ] to avoid Python standard Exception
`TypeError: 'module' object is not callable`
changed
`from odoo.tools import safe_eval`
to
`from odoo.tools.safe_eval import safe_eval`

### CODE REVIEW

**Review by ajaniszewska-dev — APPROVED** [review]

**Comment by simahawk** [comment]
please check the build

**Comment by yankinmax** [comment]
@simahawk I checked it and couldn't solve the error as it isn't related to `delivery_auto_refresh`. Unfortunately, I didn't investigate it extensively till you wrote to do it and already merged parent PR. From what I see now, after the last update, the warning message in delivery_auto_refresh has gone.

**Comment by CarlosRoca13** [comment]
Please add this fix on the migration:

- [ ] https://github.com/OCA/delivery-carrier/pull/440

**Comment by simahawk** [comment]
moving to #466

**Pull request closed without merging**
