### PR TITLE
[13.0][MIG] delivery_state

### PR DESCRIPTION
**Pull request by misern2**
Standard Migration

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review. LGTM

**Review by danimv5 — APPROVED** [review]
Functional review! LGTM

**Review by eduardgm — APPROVED** [review]
Functional review, LGTM!

**Comment by alex-guardado** [comment]
Code review & Functional review. LGTM!

**Review by alex-guardado — APPROVED** [review]

**Pull request merged**
