### PR TITLE
[ADD] [15.0] delivery_dhl_oca

### PR DESCRIPTION
**Pull request by ghost**
We are currently implementing several API's for DHL namely

	- [DHL Parcel DE Shipment Tracking (Post & Parcel Germany)](https://developer.dhl.com/api-reference/dhl-parcel-de-shipment-tracking-post-parcel-germany)
	- [DHL Parcel DE Returns (Post & Parcel Germany)](https://developer.dhl.com/api-reference/dhl-parcel-de-returns-post-parcel-germany)
	- [DHL Parcel DE Private Shipping (Post & Parcel Germany)](https://developer.dhl.com/api-reference/dhl-parcel-de-private-shipping-post-parcel-germany)

Is it possible to add them to the OCA? And is delivery_carrier the right place?
Is there anything else necessary to start a new oca module?

Please ignore fileheaders / license formating at the moment, but would warmly welcome feedback on the approach.
The attached code is working with the appropriate test credentials.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, thanks for the contribution. It seems this is something specific for Germany, so the proper place for this should be `l10n-germany`. You can call the module `delivery_dhl_de_oca` or similar.

**Comment by ghost** [comment]
How do I add "base_iso3166" from another oca module?

**Comment by pedrobaeza** [comment]
Just adding the dependency in the manifest, and generating the proper `setup` folder with pre-commit tools. https://github.com/OCA/maintainer-tools/wiki/Install-pre-commit

**Comment by pedrobaeza** [comment]
Closing this one in favor of the localization one.

**Pull request closed without merging**
