### PR TITLE
[IMP] new version of PostLogistics webservice

### PR DESCRIPTION
**Pull request by mdietrichc2c**
PostLogistics migrated their webservice to a new server; I added the new WSDL/XSD files and modified the company to use those files.

### CODE REVIEW

**Comment by guewen** [comment]
Thanks :+1:

**Comment by gurneyalex** [comment]
well... I'll trust you on the fact that this works...

**Comment by mdietrichc2c** [comment]
It's been used for 2 months in a client's instance (the development was
made at their request).
I forgot to do a PR on GitHub back then.

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
