### PR TITLE
[15.0][MIG] base_delivery_carrier_files: Migration to 15.0

### PR DESCRIPTION
**Pull request by wytzejan**

### CODE REVIEW

**Comment by wytzejan** [comment]
@pedrobaeza @rousseldenis 

Hi, this is my first full pull request for the OCA and I can not figure out how to reduce the commits. I followed the full technical process here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0 and tried to merge/squash commits like described here: https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests but I do not know how to do it. Can you help me out here? I would appreciate!

**Comment by pedrobaeza** [comment]
You don't know the procedure or which commits to squash/merge together?

**Comment by wytzejan** [comment]
The procedure. I think all commits except the one I made (ed25998 and a900dbd) should be squased/merged.

**Comment by pedrobaeza** [comment]
Then I think you are asking about what to merge. Check this image:

Selección_061

**Comment by wytzejan** [comment]
Thanks @pedrobaeza, I understand. Fixed it now.

**Comment by wytzejan** [comment]
@gurneyalex This pull request is still relevant. Can you (as PSC member) remove the stale label please? Thanks!

**Pull request closed without merging**
