### PR TITLE
[10.0][MIG] delivery_carrier_label_postlogistics_shop_logo: Migration to 10.0

### PR DESCRIPTION
**Pull request by grindtildeath**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why not integrating this on main module?

**Comment by grindtildeath** [comment]
@pedrobaeza There's already an option in the main module to add the company logo to be printed on the labels.
Considering this module inherited `sale.shop` I suppose there should be another dependency to have a different logo between different shops, but I'm only figuring it out now.

**Comment by pedrobaeza** [comment]
OK, just curiosity. Thanks for answering.

**Comment by rousseldenis** [comment]
@grindtildeath Please check travis

**Comment by grindtildeath** [comment]
As `sale.shop` model has been removed from odoo there's no need to migrate this module.

**Pull request closed without merging**
