### PR TITLE
[13.0][ADD] delivery_carrier_multi_zip: Multiple ZIP intervals for the same delivery method

### PR DESCRIPTION
**Pull request by pedrobaeza**
This module allows to set more than one interval of zip codes for matching each shipping method.

@Tecnativa TT35326

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
Code and functional review.

Looks like CI Tests are blocked by other modules' developement status deps

**Comment by pedrobaeza** [comment]
@chienandalu see #478

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
