### PR TITLE
15.0 mig delivery_price_rule_untaxed

### PR DESCRIPTION
**Pull request by leemannd**
Hello, @monen17 @Aldeigja @AshishHirapara . I'm migrating a module you have been working on. A review is welcome.

Open question. I am currently wondering if we shouldn't update the maturity level to "stable" instead of "beta"

### CODE REVIEW

**Review by cyrilmanuel — APPROVED** [review]
lgtm

**Review by StephaneMangin — APPROVED** [review]

**Review by santostelmo — APPROVED** [review]

**Review by monen17 — APPROVED** [review]
Thanks for the PR!
I reviewed the code and it looks good to me

It would be nice to https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate.

**Review by Ricardoalso — APPROVED** [review]

**Comment by leemannd** [comment]
Hello @OCA/logistics-maintainers-psc-representative a review and an eventual merge is welcome

**Comment by Ricardoalso** [comment]
> Hello @OCA/logistics-maintainers-psc-representative

Gentle Ping

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
