### PR TITLE
[15.0] [MIG] connector_routific: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT40311

please @sergio-teruel @carlosdauden review this

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
pre-commit should be fixed with https://github.com/OCA/delivery-carrier/pull/545

**Comment by sergio-teruel** [comment]
Make rebase so, the https://github.com/OCA/delivery-carrier/pull/545 was merged

**Comment by CarlosRoca13** [comment]
Done @sergio-teruel

**Comment by sergio-teruel** [comment]
Pre-commit fails again

**Comment by CarlosRoca13** [comment]
Now it is solved

**Review by sergio-teruel — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@CarlosRoca13 please rebase and fix conflicts.

**Comment by CarlosRoca13** [comment]
@pedrobaeza done!

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
