### PR TITLE
[MIG] delivery_carrier_info: Migration to 15.0

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Comment by florian-dacosta** [comment]
Hello @fshah-initos
Thanks for the contribution.
There is a problem here, the commit history is lost and it is important to preserve it.
You can follow the method described here : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0
(This step in particular `git format-patch --keep-subject --stdout origin/15.0..origin/14.0 -- $MODULE | git am -3 --keep`)

**Comment by rousseldenis** [comment]
@fshah-initos The module exists in 14.0 branch, so, why not basing your work on that (instead of 12.0) ?

**Review by dsolanki-initos — APPROVED** [review]
Code review and functional tests.
Looks good to me.

**Review by florian-dacosta — APPROVED** [review]

**Comment by ikapasi-initos** [comment]
It would be nice maintainer approve this pull.

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
