### PR TITLE
[MIG] [8.0] base_delivery_carrier_files_document

### PR DESCRIPTION
**Pull request by thomaspaulb**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@thomaspaulb Any news on this ?

**Comment by thomaspaulb** [comment]
@rousseldenis I have managed to please the runbot, would you mind reviewing?

**Review by rousseldenis — APPROVED** [review]
Code review. @thomaspaulb Could you squash your commits ?

**Comment by thomaspaulb** [comment]
@rousseldenis The migration is already in one commit, the other commits are linting and fixes for other modules. I think it's better to keep them separate in this case?

**Comment by rousseldenis** [comment]
> @rousseldenis The migration is already in one commit, the other commits are linting and fixes for other modules. I think it's better to keep them separate in this case?

You're right

**Comment by thomaspaulb** [comment]
@guewen @yvaucher I think this can be merged, no?

**Review by guewen — APPROVED** [review]
I don't remember at all the work I did here 😆

**Comment by thomaspaulb** [comment]
@bealdav [Travis](https://app.travis-ci.com/github/OCA/delivery-carrier/jobs/524961662#L1164) fails on the [GLS module which was ported by you](https://github.com/OCA/delivery-carrier/pull/91/files#diff-d337eb3652d4bfbdf055ebb13756363e3ce97df11a51a8cf45f118a43b3f2421R278).

Am I right in assuming the test actually tries to contact the GLS API, instead of using a mock?

**Comment by thomaspaulb** [comment]
@dreispt Tests are now green, so I think we could just merge this?

**Pull request closed without merging**
