### PR TITLE
[14.0][FIX] delivery_package_number: Don't reset number on backorder

### LINKED ISSUE #676: delivery_package_number bug module when creating a backorder
## Module
delivery_package_number

## Describe the bug
We have detected a bug in the delivery_package_number module when creating a backorder.

## To Reproduce
**Affected versions**:

1. Create a sales order containing at least one storable product and quantity greater than 1, example 10.
2. Confirm the sales order.
3. Go to the created delivery.
4. Enter the 'Number of Packages' in the 'Additional Info' tab, example 2.
5. Enter the packages in the 'Done' column less than 'Reserved', example 2.
6. Click on Validate and click on 'Generate Backorder' or 'No backorder' .

**Expected behavior**
If we go again to the tab 'Additional Info' the number of packages is 1 (incorrect) instead of 2 (correct).

**Additional context**
While trying to solve it we have detected that the problem is caused by the repeated execution of the _compute_number_of_packages function that recalculates the number of packages based on package_ids and sets the Number of Packages to 1 if there are no package_ids.

## Proposal
We propose the following changes to the delivery_package_number module to fix the bug:

- Create a boolean field that will appear next to the 'Number of Packages' to be able to switch between inserting the number manually or having it automatically calculated based on the package_ids. This way we avoid recalculating the 'Number of Packages' if it is in manual mode.
- On the other hand, if the company has disabled the 'Packages' in the Inventory settings, by default the option will be manual.
- In addition, we will also add a Boolean field in the 'Operation Type' to set whether it is calculated automatically or manually by default depending on the 'Type of Operation'. In this way, we will always be able to choose from the picking whether the 'Number of Packages' is inserted manually or automatically but, depending on the 'Type of Operation', there will be a default option.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
Fixes #676

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre @HaraldPanten

**Review by ValentinVinagre — COMMENTED** [review]
LGTM 👍🏻

**Review by ValentinVinagre — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Ouch, TNT module also relies on having 1 as default. You should change it.

**Comment by HaraldPanten** [comment]
> Ouch, TNT module also relies on having 1 as default. You should change it.

Yes, we'll FIX it, don't worry. We'll ping you once we prepare the PR. THX Pedro.

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
We were rebasing just 1 minute before merge command. I supose it'll not be a problem  🤔

**Comment by pedrobaeza** [comment]
You don't need to rebase. The merge command rebases your branch over latest changes on target branch, so better to not waste a build. A rebase is needed for manual verifications or using latest code on runboat, but here, which is clear that the CI is fixed and the code of this PR is OK, we just need to launch the merge command.

**Comment by HaraldPanten** [comment]
> You don't need to rebase. The merge command rebases your branch over latest changes on target branch, so better to not waste a build. A rebase is needed for manual verifications or using latest code on runboat, but here, which is clear that the CI is fixed and the code of this PR is OK, we just need to launch the merge command.

Yes, we know that the new branch will run the tests as well. And it would be so strange to fail, as few minutes ago, the other FIX PR has been merged in the same branch without any problem. But you know... just in case...

**Comment by pedrobaeza** [comment]
It's not just that they run the CI. It rebases the branch, so that's the key.

**Comment by HaraldPanten** [comment]
> It's not just that they run the CI. It rebases the branch, so that's the key.

We know that. But, as I said... just in case 🤷

**Pull request merged**
