### PR TITLE
[11.0] Migrate base_delivery_carrier_label

### PR DESCRIPTION
**Pull request by hugosantosred**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please squash a bit commit history, joining them by logical set/author?

**Comment by hugosantosred** [comment]
Squash done, I've squashed the commit history grouping by author.

**Comment by pedrobaeza** [comment]
I still see 70 commits and several together from same author...

**Comment by pedrobaeza** [comment]
You can join also 3 that are:

OCA Transbot ...
Remove en.po ...
OCA Transbot ...

Because they are all about translations (one is an amend).

**Comment by yvaucher** [comment]
This squashing is a bit to harsh, I think you should focus mainly on squashing the translation commits, all the rest can mainly stay.

If you want to squash more, please keep in mind the changesets.
Fixup can be part of a changeset and can be squashed.
The best way to identify it is if they were in the same pull request.

**Comment by asaunier** [comment]
A minor remark: the first line ``# -*- coding: utf-8 -*-`` is no longer needed in Python 3 (see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#tasks-to-do-in-the-migration)

**Comment by asaunier** [comment]
Suggested replacement PR squashing (a few) i18n commits and removing the utf-8 headers: https://github.com/OCA/delivery-carrier/pull/154

**Pull request closed without merging**
