### PR TITLE
[10.0][ADD] delivery_carrier_partner: Add transporter field

### PR DESCRIPTION
**Pull request by SimoRubi**
The field was removed between v9 and v10 by Odoo with https://github.com/odoo/odoo/commit/d32abe75b16eb215f8c2bdf5682fd7bdb7238c4d.

This module adds this field back (but not `required`) because it may be useful to contact the company/person making the delivery.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by tafaRU — CHANGES_REQUESTED** [review]
LGTM except for the name of `delivery.py` and `delivery.xml `.

According to https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#15file-naming I'd prefer to remane them respectively to `delivery_carrier.py` and `delivery_carrier.xml`.

**Comment by SimoRubi** [comment]
@tafaRU done in https://github.com/OCA/delivery-carrier/pull/171/commits/2e70200494466674f190634b703b8d4eb8e26fa5

**Comment by tafaRU** [comment]
Ok, thanks @SimoRubi.
Could you also please add `installable` key to the manifest file?

**Comment by SimoRubi** [comment]
@tafaRU done in https://github.com/OCA/delivery-carrier/pull/171/commits/5bfe1ac6e6b16296f17a661feb6808efe9492ca5

**Review by tafaRU — APPROVED** [review]

**Comment by SimoRubi** [comment]
Fixed up commits

**Review by eLBati — APPROVED** [review]

**Comment by celm1990** [comment]
HI, any plan to migrate this module to V12????

**Comment by SimoRubi** [comment]
@celm1990 looking through the open PRs, there is already https://github.com/OCA/delivery-carrier/pull/221, a review might speed up the merging process :)

**Pull request merged**
