### PR TITLE
[14][MIG] mig carrier_environment

### PR DESCRIPTION
**Pull request by florian-dacosta**
Renamed `carrier_account_environment` to avoid confusion with `server_environment_delivery`
Also, changed repo from server-env to dleivery-carrier for consistency with `server_environment_delivery`

### CODE REVIEW

**Comment by florian-dacosta** [comment]
@hparfr @bealdav @sebastienbeau 
Please review!

**Comment by sebastienbeau** [comment]
Lgtm code review. Ok for the new name, it's better

**Review by sebastienbeau — APPROVED** [review]
Lgtm code review. Ok for the new name, it's better

**Review by rousseldenis — CHANGES_REQUESTED** [review]
Seems great. @florian-dacosta Could you include commit history from server-env ? Thanks

**Comment by florian-dacosta** [comment]
Done @rousseldenis

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
