### PR TITLE
[14.0][MIG] delivery_auto_refresh: Migration to 14.0

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
based on https://github.com/OCA/delivery-carrier/pull/466

Updated tests

### CODE REVIEW

**Review by elvise — APPROVED** [review]
LGTM

**Review by chienandalu — COMMENTED** [review]
I'm missing 50ced506c480dcb7bef5598c45bab6dbc33a393d and 27ffc443bfe246ac7c79d9616a1daa4db109fd1c

**Comment by simahawk** [comment]
@ilyasProgrammer please, do not add "Merge" commits.
Also, I'm not sure this kind of fix is really nice https://github.com/OCA/delivery-carrier/pull/472/commits/da545e5d5282c4ee1985be1dc5d73c3dd1df665a
Any other opinion?

**Comment by chienandalu** [comment]
> Also, I'm not sure this kind of fix is really nice https://github.com/OCA/delivery-carrier/commit/da545e5d5282c4ee1985be1dc5d73c3dd1df665a
Any other opinion?

Yes, not the best way to do it. If this module's default values is interfering with other modules tests it would be better to set saner defaults or remove demo data that would provoke that.

**Comment by elvise** [comment]
> > Also, I'm not sure this kind of fix is really nice https://github.com/OCA/delivery-carrier/commit/da545e5d5282c4ee1985be1dc5d73c3dd1df665a
> 
> Any other opinion?
> 
> 
> 
> Yes, not the best way to do it. If this module's default values is interfering with other modules tests it would be better to set saner defaults or remove demo data that would provoke that.

@ilyasProgrammer what do you think can you fix it ?

**Comment by simahawk** [comment]
> > Also, I'm not sure this kind of fix is really nice [da545e5](https://github.com/OCA/delivery-carrier/commit/da545e5d5282c4ee1985be1dc5d73c3dd1df665a)
> > Any other opinion?
> 
> Yes, not the best way to do it. If this module's default values is interfering with other modules tests it would be better to set saner defaults or remove demo data that would provoke that.

Yeah, if it's about default values I'd rather tweak them or activate its behavior explicitly w/ a flag on the company or any other kind of configuration that might suit.

**Comment by ilyasProgrammer** [comment]
I'll try to find configuration-based variant to solve this.

**Comment by ilyasProgrammer** [comment]
moved here https://github.com/OCA/delivery-carrier/pull/473

**Pull request closed without merging**
