### PR TITLE
10.0 mig delivery carrier deposit

### PR DESCRIPTION
**Pull request by EBII**

### CODE REVIEW

**Comment by bealdav** [comment]
CI/runbot log result:

Module test summary
[1;32mSuccess[0;m delivery_carrier_b2c,delivery_carrier_deposit,base_delivery_carrier_label

+=======================================
|  Tests summary:
|---------------------------------------
| test_server.py              [1;32mSuccess[0;m
+=======================================

and the odoo instance works perfectly with this module: just tried it

Then successful, no ?

thanks for review

**Comment by bealdav** [comment]
ping @hpar tests are green, thanks for a review

**Review by mourad-ehm — APPROVED** [review]

**Review by hparfr — APPROVED** [review]

**Comment by mourad-ehm** [comment]
Hi @sebastienbeau, could you merge this PR please ?

**Comment by florian-dacosta** [comment]
Hey, before merging, could you consider this fix?
https://github.com/OCA/delivery-carrier/pull/149

**Comment by sebastienbeau** [comment]
@florian-dacosta merged with your fix

**Comment by alexis-via** [comment]
The last-minute fix broke it all. I fixed it here: https://github.com/OCA/delivery-carrier/pull/151/files
@sebastienbeau Could you merge this obvious fix ?

**Pull request merged**
