### PR TITLE
[MIG][9.0] Port delivery_carrier_deposit

### PR DESCRIPTION
**Pull request by hparfr**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Have you used this method: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0?

**Comment by hparfr** [comment]
No. I didn't was aware of it.
I Will read it.

**Comment by hparfr** [comment]
Ok now.
I did some minor changes to be compliant with the guidelines.

I did not commit any tests because it's hard to write. Due to the nature of this module and the dependency graph; it can't be unittested alone.

**Comment by mourad-ehm** [comment]
:+1:

**Comment by bealdav** [comment]
:+1:

**Pull request merged**
