### PR TITLE
[12.0][IMP] delivery_carrier_label_paazl: split methods

### PR DESCRIPTION
**Pull request by astirpe**
This is a proposal of splitting methods to ease customizations.

CC @hbrunn

### CODE REVIEW

**Review by hbrunn — APPROVED** [review]
I think this is okay as it is, but wouldn't it be more convenient for the user (=programmer) of this module when you do the looping in `_paazl_order_send` and the functions you introduce operate on self?

**Comment by astirpe** [comment]
@hbrunn do you mean this?

```python
    def _paazl_send(self):
        result = []
        for this in self:
            this._paazl_check_picking_consistency()
            this._set_a_default_package()
            this._paazl_send_update_order()
            result.append(this._paazl_generate_labels())
        return result
```

**Review by hbrunn — APPROVED** [review]
exactly!

**Comment by astirpe** [comment]
@hbrunn I think it's good to have `_paazl_check_picking_consistency()` and `_set_a_default_package()` outside the loop, so that it will be ensured that all the pickings have consistent data before starting to exchange data with Paazl.

**Comment by astirpe** [comment]
@hbrunn I added this commit https://github.com/OCA/delivery-carrier/pull/372/commits/23f0206150e993faa243a1feb428d4f8e315dceb, to allow to update the order data. Do you agree with it? And if you agree, do you think it's worth a separate PR?

**Comment by astirpe** [comment]
@hbrunn do you agree with https://github.com/OCA/delivery-carrier/pull/372/commits/49cb363f3c92a8cfd4efe79811c33e6fe91b22c1 ?

**Comment by hbrunn** [comment]
@astirpe totally. If you keep working on this, would it make sense to mark your PR as draft? Then new commits don't generate a notification for subscribers

**Review by dkubiak789 — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
@astirpe can you squash commits?

**Comment by astirpe** [comment]
@StefanRijnhart squashed, thanks!

**Comment by StefanRijnhart** [comment]
@astirpe thanks!

/ocabot merge patch

**Pull request merged**
