### PR TITLE
[13.0][FIX] delivery_auto_refresh: Fix error when adding products to cart on website

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa 

Ping @chienandalu @pedrobaeza

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why not adding automatically the delivery line? Steps to reproduce the problem? We should handle it other way if not, but the feature should be kept.

**Comment by chienandalu** [comment]
STR are:

- Set `delivery_auto_refresh.auto_add_delivery_line`
- Set a default delivery method on the user's partner.
- Place a new ecommerce order with that user adding to the cart:

``` 
Error message:

Record does not exist or has been deleted.
(Record: sale.order.line(63,), User: 1)
```

We didn't dive deep into the cause (I guess there's an unlink method over there causing a race condition). Anyway, in an ecommerce context makes no sense to add the line automatically, as the user will be choosing the proper delivery method in the end...

**Comment by pedrobaeza** [comment]
OK, got it, and you are right

**Comment by pedrobaeza** [comment]
@CarlosRoca13 please put these steps to reproduce in the commit message, and a comment in code in the if for saying that having such context means that the order is being done in the e-commerce.

**Review by chienandalu — COMMENTED** [review]
@CarlosRoca13 add some comments on the code, please

**Comment by CarlosRoca13** [comment]
Done @chienandalu @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please fw-port it to v14:

/ocabot merge patch

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
