### PR TITLE
[13.0][MIG] delivery_dropoff_site

### PR DESCRIPTION
**Pull request by acsonefho**
Migration of the module `delivery_dropoff_site` (based on open PR https://github.com/OCA/delivery-carrier/pull/244 about `12.0`).

- [x] Use OCA guideline to migrate the module;
- [x] Migrate to `13.0`;
- [x] Use api.model_create_multi when possible;
- [x] Use new `super()` syntax;
- [x] No error/warning during install;
- [x] pre-commit.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@acsonefho Can you fix runbot warning? It's about model _description missing field

**Review by ThomasBinsfeld — APPROVED** [review]

**Comment by rousseldenis** [comment]
@acsonefho Please check https://runbot2.odoo-community.org/runbot/static/build/3436478-281-091d3e/logs/job_20_test_all.txt

Warning at the end about two fields having the same label.

`2020-08-24 08:50:53,499 158 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (property_delivery_carrier_id, carrier_id) of dropoff.site() have the same label: Delivery Method.`

**Review by ThomasBinsfeld — APPROVED** [review]

**Comment by ThomasBinsfeld** [comment]
@rousseldenis Warning should be fixed

**Comment by rousseldenis** [comment]
@acsonefho Could you rebase ?

**Comment by rousseldenis** [comment]
@acsonefho

**Comment by flotho** [comment]
ping @vincent-mundo @gaelTorrecillas @MalikaBelmokhtar please could you review this to prepare v14 migration

**Comment by flotho** [comment]
ping @BechirAouji 
A Review is also expected from you .

**Comment by flotho** [comment]
hi @acsonefho @pedrobaeza @sbidoul , how is it possible to force a runBOAT execution for this one?

Regards

**Comment by flotho** [comment]
Hi @acsonefho any chance to update your unit tests?
Do you have time for this?

**Comment by acsonefho** [comment]
> Hi @acsonefho any chance to update your unit tests? Do you have time for this?

Hi @flotho I don't have time today and I'm off during a couple of week so don't hesitate to do it.

**Comment by sbidoul** [comment]
@flotho normally triggering a build is done by pushing a commit.

In exceptional situation, it is doable also via https://runboat.odoo-community.org/docs, but you need a login - which I'd be happy to share with regular contributors, I just don't have a convenient way to do it. So I just triggered the build for this PR.

**Pull request closed without merging**
