### PR TITLE
[MIG][WIP][10.0] delivery_carrier_label_gls

### PR DESCRIPTION
**Pull request by angelmoya**

### CODE REVIEW

**Comment by bealdav** [comment]
ping @jeanpaulrobineau

**Comment by jeanpaulrobineau** [comment]
Hello Mr Beal,

I am sorry but apparently it is not possible to make a delivery carrier for
GLS Belgium.
I have contacted GLS directly and they have told me they don't allow this.

Kind regards,
Jean-Paul Robineau

2017-03-30 12:58 GMT+02:00 David Beal <notifications@github.com>:

**Comment by angelmoya** [comment]
@bealdav and @jeanpaulrobineau you can also check this PR https://github.com/OCA/server-tools/pull/798 for configuration_helper

**Comment by angelmoya** [comment]
Also this PR depends from https://github.com/OCA/partner-contact/pull/402

**Comment by angelmoya** [comment]
And #124

**Comment by angelmoya** [comment]
@bealdav and @jeanpaulrobineau I will not continue with this work, because in Spain neither is possible to use this webservices.

I will start a new module carrier_files_gls because in Spain this integration is over other app with csv file interchange

**Pull request closed without merging**
