### PR TITLE
MIG 15.0 delivery_price_method

### PR DESCRIPTION
**Pull request by jaredkipe**

### CODE REVIEW

**Comment by victoralmau** [comment]
Hi, will you continue with the PR and solve the pre-commit errors?

**Comment by victoralmau** [comment]
Superseed by https://github.com/OCA/delivery-carrier/pull/536

**Comment by rousseldenis** [comment]
@jaredkipe

**Comment by chienandalu** [comment]
The superseed was already migrated. This can be closed

**Pull request closed without merging**
