### PR TITLE
[11.0][MIG] delivery_multi_destination: Migration to 11.0

### PR DESCRIPTION
**Pull request by pedrobaeza**
* Standard procedure
* README by fragments
* Code changed to follow v11 logic
* Tests adapted and expanded

cc @Tecnativa

### CODE REVIEW

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Review by chienandalu — COMMENTED** [review]
¿no runbot?

**Comment by pedrobaeza** [comment]
Uhm, probably there's something to do with .travis.yml. I'll check.

**Comment by pedrobaeza** [comment]
No, Travis is correct. Please review code.

**Review by tarteo — APPROVED** [review]

**Pull request merged**
