### PR TITLE
delivery_carrier_label_dispatch - save picking dispatch label pdf file as attachement of the picking

### PR DESCRIPTION
**Pull request by guewen**
I moved this PR from Launchpad [0] on behalf of @yvaucher, he's the author.

[0] https://code.launchpad.net/~camptocamp/carriers-deliveries/7.0-delivery_carrier_label_dispatch-output-file-yvr/+merge/202444

### CODE REVIEW

**Comment by guewen** [comment]
Travis fails due to long lines: fixed here https://github.com/OCA/carrier-delivery/pull/29

**Comment by guewen** [comment]
Rebased after correction of long lines in another PR.

**Comment by yvaucher** [comment]
:+1:

**Comment by yvaucher** [comment]
We had one approve on LP from @lepistone

**Comment by lepistone** [comment]
@yvaucher I think we can merge then. thanks

**Pull request merged**
