### PR TITLE
[FIX] base_delivery_carrier_label: compute the weight by the product weight

### PR DESCRIPTION
**Pull request by yankinmax**

### CODE REVIEW

**Comment by yankinmax** [comment]
@florian-dacosta can you pls take a look?

**Review by florian-dacosta — APPROVED** [review]

**Comment by yankinmax** [comment]
@florian-dacosta do you want me to change the tests? They seem OK for me.

**Comment by florian-dacosta** [comment]
Hum, I went too fast, I did not see the test was failing... I'll take a look

**Comment by florian-dacosta** [comment]
@yankinmax I made a PR on your branch to fix the tests.

**Comment by yankinmax** [comment]
@florian-dacosta you rock!! Why didn't I check product types?? :smile:

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
