### PR TITLE
[14.0][MIG] delivery_postlogistics_server_env

### PR DESCRIPTION
**Pull request by hailangvn**
Depends on:
* `delivery_postlogistics`: https://github.com/OCA/delivery-carrier/pull/377

### CODE REVIEW

**Comment by hailangvn** [comment]
The runbot is green at https://runbot.odoo-community.org/runbot/branch/2470465.

**Review by sebalix — APPROVED** [review]

**Comment by simahawk** [comment]
@hailangvn can you drop the TMP dep?

**Comment by hailangvn** [comment]
Good day @simahawk, the PR has been rebased without TMP dep. Thanks.

**Pull request merged**
