### PR TITLE
[14.0][MIG] delivery_carrier_label_batch - Migration to 14.0

### PR DESCRIPTION
**Pull request by kv1612**
Depends on:
- https://github.com/OCA/stock-logistics-workflow/pull/943

### CODE REVIEW

**Review by leemannd — APPROVED** [review]
Technical review

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]
Don't forget to remove https://github.com/OCA/delivery-carrier/pull/452/commits/29b7bdbb12653e62c4a54b57b91637a4386368bd before merging

**Comment by khoivo1601** [comment]
This PR is replaced by the PR #468. One small update is change the [action_generate_carrier_label](https://github.com/OCA/delivery-carrier/pull/452/files#diff-6ebd108538510e3e3639b6099284c6798eacd4f02b70160af4c2b6e069fa2cfeR84) method to the [send_to_shipper](https://github.com/OCA/delivery-carrier/pull/468/commits/939b8aa9fad7028b0759077f59034a1284942327#diff-6ebd108538510e3e3639b6099284c6798eacd4f02b70160af4c2b6e069fa2cfeL85) method (I have a problem with 2FA. So, I can't login to update this PR directly. Sorry for the inconvenience)

**Comment by rousseldenis** [comment]
@khoivo1601

**Pull request closed without merging**
