### PR TITLE
[15.0][IMP] partner_delivery_zone: Add delivery zone field in sale tree view

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT41262

ping @CarlosRoca13 @ernestotejeda

### CODE REVIEW

**Comment by sergio-teruel** [comment]
failed tests unrelated with this PR

**Comment by pedrobaeza** [comment]
You can indicate next time which problem is for not having to see logs. It seems a temporary failure in CTT express service, so retrying later will work.

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :+1:

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
