### PR TITLE
[IMP] partner_delivery_zone: Sync delivery zone between order and picking

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT25428
Cherry pick from v12.0 https://github.com/OCA/delivery-carrier/commit/9e3b97d9a5554cd753f05ce6b89fe46f58e2c24c

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Aren't you able to do it in the same existing compute comparing values?

**Review by joao-p-marques — APPROVED** [review]

**Review by victoralmau — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@sergio-teruel what about my question about using compute and `_origin`?

**Comment by sergio-teruel** [comment]
I have not been able to study it yet

**Review by gurneyalex — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's merge it as is for at least having the sync:

/ocabot merge patch

**Pull request merged**
