### PR TITLE
[15.0][IMP] partner_delivery_schedule: Tests more resilient

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

ping  @chienandalu @carlosdauden

### CODE REVIEW

**Comment by sergio-teruel** [comment]
Fails due to delivery_cttexpress.

**Comment by chienandalu** [comment]
Please retry @sergio-teruel

**Review by chienandalu — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@sbidoul the ocabot seems stuck again

**Pull request merged**
