### PR TITLE
[12.0][MIG][WIP] partner_delivery_zone

### PR DESCRIPTION
**Pull request by antoniorubiopesol**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Check Travis status.

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by angelmoya** [comment]
@pedrobaeza @rousseldenis @sergio-teruel 

What do you think about add delivery zone on picking list and kanban views?

**Comment by pedrobaeza** [comment]
@angelmoya OK for me

**Comment by sergio-teruel** [comment]
@angelmoya good

**Comment by angelmoya** [comment]
Ok, @antoniorubiopesol  will do it

**Comment by rousseldenis** [comment]
Ok

**Review by angelmoya — APPROVED** [review]
:+1:

**Pull request merged**
