### PR TITLE
[MIG] delivery_carrier_pricelist: Migration to 14.0

### PR DESCRIPTION
**Pull request by phuctranfxvn**
Standard migration from https://github.com/OCA/delivery-carrier/pull/279

### CODE REVIEW

**Comment by tarbib** [comment]
Delivery product at 10 and 66% off. Functional tests are ok ! :+1: 


https://user-images.githubusercontent.com/2255433/114381280-3b256d00-9b8b-11eb-9b07-761c9b52681b.mp4

**Review by gurneyalex — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Comment by simahawk** [comment]
@phuctranerp can you check what's wrong w/ the build?

**Comment by hailangvn** [comment]
Thanks for your note. I am checking this.

**Comment by hailangvn** [comment]
Good day @simahawk, I rebased the PR and it passed the test that was failed in merge build. Please help to merge again to see if the issue persist. Thank you in advance.

**Comment by nilshamerlinck** [comment]
Hi @simahawk can you retry the merge? Not sure if there was some sort of race condition originally at play; now the build is failing because the branch created by the bot doesn't exist anymore

**Comment by simahawk** [comment]
@sbidoul could you check what's wrong here https://app.travis-ci.com/github/OCA/delivery-carrier/jobs/531179822#L1483

BTW I wonder if we should silent `vcr.cassette` logging in tests :thinking:

**Comment by nilshamerlinck** [comment]
@simahawk sounds like a good workaround indeed, at least for the case that creates the issue. Pushed PR to do so here: https://github.com/OCA/delivery-carrier/pull/404

**Comment by nilshamerlinck** [comment]
Hi @simahawk the merge should be smooth now :)

**Comment by simahawk** [comment]
@nilshamerlinck one more little step :sweat_smile:

**Comment by hailangvn** [comment]
@simahawk, The pre-commit should be good now.

**Pull request merged**
