### PR TITLE
[14.0][FIX] delivery_tnt_oca: delivery_package_number compatibility

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
Fix tests to declare packages explicitly
Fix test PR https://github.com/OCA/delivery-carrier/pull/702

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by victoralmau — APPROVED** [review]
Ok, fix similar to what was done at https://github.com/OCA/l10n-spain/pull/3225/files#diff-58dc9b73d24b0ce5db13a41c0fcbeac3da1ec17b407ed98f4b4d3de26a0dda4fR46

**Pull request merged**
