### PR TITLE
[15.0][MIG] delivery_carrier_partner

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hello @hbrunn ,

Sorry for asking, I would like to test it and I'm new with this module.

1. I've read the README but I don't get the use purpose of the module. The rationale is for assigning a Drivers to the Delivery Method? Not blocking just for testint! 😄 
2. Could you please rebase to build runboat and test?

Thank you! ❤️

**Comment by hbrunn** [comment]
@rafaelbn see [the original PR](https://github.com/OCA/delivery-carrier/pull/171), here you can store contact info of the company doing the delivery to contact them in case of problems

**Comment by rafaelbn** [comment]
Thank you @hbrunn ! This is not what I'm looking for 😄 as we want "Drivers" but I've tested! 👍🏼

**Review by rafaelbn — APPROVED** [review]
Functionall review 👍🏼

**Review by dreispt — APPROVED** [review]

**Pull request merged**
