### PR TITLE
[15.0][MIG] delivery_cttexpress: Migration to 15.0 

### PR DESCRIPTION
**Pull request by chienandalu**
- Standard migration

cc @Tecnativa TT39099

@victoralmau @pedrobaeza please review

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]
Code review OK.

Can you update translations (at least in Spanish)?

**Comment by chienandalu** [comment]
Ok, I'll do it :+1:

**Comment by chienandalu** [comment]
Done!

**Review by victoralmau — APPROVED** [review]

**Pull request merged**
