### PR TITLE
[13.0][IMP] delivery_*: Promote modules to Stable

### PR DESCRIPTION
**Pull request by pedrobaeza**
@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@victoralmau do you know the error in UPS?:

https://github.com/OCA/delivery-carrier/runs/6116997723?check_suite_focus=true#step:8:407

**Comment by rousseldenis** [comment]
@pedrobaeza I think the problem is the logged user:

image

**Comment by pedrobaeza** [comment]
Oh, I see, thanks. I have retried now to see if it's unlocked.

**Comment by pedrobaeza** [comment]
The same problem. It seems somebody has blocked the test user using a wrong password, and it locks out the same as the rest of the users. @victoralmau can you try to contact UPS technical support for unlocking it and eventually ask for avoiding such lock?

**Comment by victoralmau** [comment]
> The same problem. It seems somebody has blocked the test user using a wrong password, and it locks out the same as the rest of the users. @victoralmau can you try to contact UPS technical support for unlocking it and eventually ask for avoiding such lock?

Exactly, the user seems to be blocked. I have sent an email to UPS technical support to try to unlock it.

**Comment by pedrobaeza** [comment]
Víctor, any news from UPS?

**Comment by victoralmau** [comment]
Nothing important, maybe we can create an issue on this subject so that odoo can update it.

**Pull request merged**
