### PR TITLE
[ADD] delivery_optional_invoice_line module v.7.0

### PR DESCRIPTION
**Pull request by tafaRU**
Moving the MP: https://code.launchpad.net/~agilebg/carriers-deliveries/adding_delivery_optional_invoice_line_7/+merge/213867

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1: x3 on launchpad

Thanks for the port

**Comment by tafaRU** [comment]
Great!! Thank you, @yvaucher.

**Comment by guewen** [comment]
@tafaRU Can you rebase so travis will build the PR?

**Comment by tafaRU** [comment]
@guewen why do I need to rebase if the PR is already merged?

Thank you in adavance.

**Comment by guewen** [comment]
@tafaRU Actually I don't know. I missed something it seems 
:confused:

**Pull request merged**
