### PR TITLE
[16.0][IMP] improve logging

### PR DESCRIPTION
**Pull request by sbidoul**
Better use of logging so tools like sentry deduplicate the message.

### CODE REVIEW

**Comment by sbidoul** [comment]
Red because of the ctt express integration is broken?

Why don't we use `vcr` to test such integration? At least tests are stable, and it's easy to update the cassettes when the upstream api evolves.

**Comment by pedrobaeza** [comment]
We want to test the real thing. You will have it green very soon. Just retry in half an hour.

**Comment by sbidoul** [comment]
> We want to test the real thing

With vcr you test the real thing. You just record it in your test so the test suite does not hit the network.

And any time you want you can re-record with the real thing. But at least you do it in a controlled manner and don't disturb unrelated contributions.

**Comment by pedrobaeza** [comment]
But it's a frozen version of the reality. As said, we want to know if there's an API change or a problem in the service.

**Comment by rvalyi** [comment]
For the record we had this questionning in l10n-brazil. A trade off we found is to use a special decorator so the test against the external server is performed only once a week and the other days a mocked version is tested.

The only big drawback of this approach is the test coverage percent changes a bit depending on the scenario, so PRs can be red because they have 0.1% test coverage...

**Comment by sbidoul** [comment]
Then you need one repo per integration, with scheduled pipelines. Because as it is now you discover changes randomly when there are contributions on unrelated modules, and that is just annoying poor contributors like me :)

**Comment by pedrobaeza** [comment]
And for me it's also very annoying to deal with all the PIP/wheel/etc stack random failing, but I have learned to live with it...

**Comment by pedrobaeza** [comment]
They haven't still fixed it, so that means right now the service is not working for any customer. I have already told him, so I'll launch the merge command as soon as they fix it.

**Pull request merged**
