### PR TITLE
[17.0][MIG] base_delivery_carrier_label

### PR DESCRIPTION
**Pull request by David-Luis-Mora**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@David-Luis-Mora Thanks for this. Could you check tests ?

**Comment by yankinmax** [comment]
@David-Luis-Mora Can you pls double check the dependency: `delivery` should be `stock_delivery` as it has been changed in v17.
And fix the views: 
```
<record id="view_picking_withcarrier_out_form" model="ir.ui.view">
    <field name="model">stock.picking</field>
    <field name="inherit_id" ref="delivery.view_picking_withcarrier_out_form" />
    <field name="arch" type="xml">
        <xpath expr="//page//field[@name='carrier_id']" position="after">
            <field name="carrier_code" />
            <field
                name="option_ids"
                domain="[('carrier_id', '=', carrier_id)]"
                widget="many2many_tags"
                options="{'color_field': 'color', 'no_create_edit': True}"
            />
        </xpath>
    </field>
</record>
```
Should inherit from `stock_delivery.view_picking_withcarrier_out_form`
Also `stock_delivery.vpicktree_view_tree`
Can you pls update?

**Comment by yankinmax** [comment]
@David-Luis-Mora if you don't have time I can open a new PR to supersede yours and finish the job. Thanks in advance

**Comment by yankinmax** [comment]
@David-Luis-Mora @rousseldenis 
I've opened another PR including fixes of this one to speed up migration:
- [ ] https://github.com/OCA/delivery-carrier/pull/828

**Comment by rousseldenis** [comment]
@yankinmax I think we can close this as @David-Luis-Mora has no more activity on github.

**Pull request closed without merging**
