### PR TITLE
[16.0][IMP] delivery_package_number: Allow set package numbers at confirm and new labels

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT45428

FW-PORT of https://github.com/OCA/delivery-carrier/pull/730

ping @chienandalu @sergio-teruel

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Tested :+1: (the fw is from https://github.com/OCA/delivery-carrier/pull/730 :)

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge major

**Comment by ValentinVinagre** [comment]
@pedrobaeza @CarlosRoca13 @chienandalu  can you give more details about the improvement? There is nothing explained in the readme about the new functionality, thanks.

**Comment by pedrobaeza** [comment]
There was some flows that don't present you the number of packages. Now all of them do it. The major improvement is the possibility of printing a label (a report) from the wizard repeated the number of times the package number.

**Comment by ValentinVinagre** [comment]
Thanks for the explanation Pedro, could you add it to the readme file? thanks 😸

**Comment by pedrobaeza** [comment]
Not now. You are welcome to do it if you want.

**Pull request merged**
