### PR TITLE
[14.0][MIG] delivery_carrier_label_batch - Migration to 14.0

### PR DESCRIPTION
**Pull request by khoivo1601**
Depends on:
- https://github.com/OCA/stock-logistics-workflow/pull/943

### CODE REVIEW

**Comment by khoivo1601** [comment]
This PR to replace the PR #452. One small update is change the [action_generate_carrier_label](https://github.com/OCA/delivery-carrier/pull/452/files#diff-6ebd108538510e3e3639b6099284c6798eacd4f02b70160af4c2b6e069fa2cfeR84) method to the [send_to_shipper](https://github.com/OCA/delivery-carrier/pull/468/commits/939b8aa9fad7028b0759077f59034a1284942327#diff-6ebd108538510e3e3639b6099284c6798eacd4f02b70160af4c2b6e069fa2cfeL85) method (I have a problem with 2FA. So, I can't login to update the PR #452 directly. Sorry for the inconvenience)

**Review by santostelmo — APPROVED** [review]

**Review by StephaneMangin — APPROVED** [review]

**Comment by sebalix** [comment]
@khoivo1601 dependency has been merged, can you remove [[TMP]](https://github.com/OCA/delivery-carrier/pull/468/commits/f831c4ebeb2cd1fff901bd2a4df3d7a9f4075e9a) commit?

**Comment by khoivo1601** [comment]
Hi @sebalix, the commit [[TMP]](https://github.com/OCA/delivery-carrier/pull/468/commits/f831c4ebeb2cd1fff901bd2a4df3d7a9f4075e9a) has been removed.

**Comment by sebalix** [comment]
@khoivo1601 thanks!

/ocabot merge nobump

**Pull request merged**
