### PR TITLE
Fix error when user has no language

### PR DESCRIPTION
**Pull request by guewen**
Set default language to 'en_US' when the user has no language

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: 

Thanks for the tests

**Comment by charbeljc** [comment]
Hi @pedrobaeza could we have this merged ? Regards, and good week-end

**Comment by pedrobaeza** [comment]
We need 2 approvals for merging, but as tests has been provided and the change is pretty clear, I fast-track.

**Comment by charbeljc** [comment]
Yes  @pedrobaeza ! many thanks

**Pull request merged**
