### PR TITLE
[17.0][MIG] delivery_roulier_option: Migration to 17.0

### PR DESCRIPTION
**Pull request by yankinmax**
Depends on:
- [x] https://github.com/OCA/delivery-carrier/pull/828
- [x] https://github.com/OCA/delivery-carrier/pull/827
- [x] https://github.com/OCA/delivery-carrier/pull/826

### CODE REVIEW

**Review by vvrossem — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Review by Camille0907 — APPROVED** [review]
Migration technically LGTM

**Review by hparfr — APPROVED** [review]

**Review by florian-dacosta — APPROVED** [review]

**Pull request merged**
