### PR TITLE
12.0 FIX base_deliv_label: use valid qty to compute weight of move.line

### PR DESCRIPTION
**Pull request by bealdav**
small fix

cc @hbrunn @florian-dacosta @hparfr @sebastienbeau @pedrobaeza

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I wonder if instead this change, the problem is when this is called (before being validated instead of after).

**Comment by bealdav** [comment]
Hi @pedrobaeza good question. We have many clients using this module with several versions. Some of them have real good reasons (I don't remember exactly which) to generate labels before or after picking done. Odoo exists for that. Make everybody happy with its marginal behavior ;-)

**Review by pedrobaeza — APPROVED** [review]
OK then :)

**Review by hbrunn — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
