### PR TITLE
[12.0][FIX] delivery_state: cron

### PR DESCRIPTION
**Pull request by chienandalu**
We were running the cron action over an empty recordset. Anyway code complexity can be reduced as we're repeating `tracking_state_update` method code.

cc @Tecnativa TT39099

please review @victoralmau @pedrobaeza

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Do you know the reason of the previous code splitting by delivery_type?

**Comment by chienandalu** [comment]
> Do you know the reason of the previous code splitting by delivery_type?

Shame on me. To discard those without a carrier with the `tracking_state_update` wildcard method. But this is already done in the caller method, so there's no need to do it twice.

**Comment by pedrobaeza** [comment]
But I think it still applies: there can be carriers that don't implement `<carrier>_tracking_state_update` method

**Review by victoralmau — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Forget my last comment. I see it's checked later.

**Pull request merged**
