### PR TITLE
[14.0][FIX] base_delivery_carrier_files: Reset cursor back for StringIO()

### PR DESCRIPTION
**Pull request by Kiplangatdan**

### CODE REVIEW

**Comment by Kiplangatdan** [comment]
@thomaspaulb This fixes the binary data when you have multiple `rows`

**Comment by thomaspaulb** [comment]
To be more complete, for other reviewers to understand:

**Problem was**: The lines in the generated carrier file had a bunch of leading ASCII 0x00 characters, the amount of which was increasing for each subsequent line. This caused the file to become seen as binary instead of text, plus have a lot of useless content.

**Review by thomaspaulb — APPROVED** [review]

**Comment by thomaspaulb** [comment]
@ntsirintanis @NL66278 Mind reviewing also

**Comment by rousseldenis** [comment]
@Kiplangatdan Maybe a test that highlight this change ?

**Review by ntsirintanis — APPROVED** [review]

**Comment by thomaspaulb** [comment]
@OCA/logistics-maintainers Could this be merged?

**Pull request merged**
