### PR TITLE
9.0 default label

### PR DESCRIPTION
**Pull request by mFlayyan**

### CODE REVIEW

**Comment by mFlayyan** [comment]
@thomaspaulb

**Comment by thomaspaulb** [comment]
@mflayyan Shouldn't this be targeted at 10.0 branch?

**Comment by mFlayyan** [comment]
@thomaspaulb yes it should

**Comment by rousseldenis** [comment]
@mFlayyan Are you sure of branch changing ? Isn't just the manifest version that has to be changed ?

**Comment by mFlayyan** [comment]
@rousseldenis yes it is targeted to v10.0 migrations from 9.0

**Comment by thomaspaulb** [comment]
@rousseldenis The 9.0 version is [here](https://github.com/OCA/delivery-carrier/pull/100)

**Comment by thomaspaulb** [comment]
@mflayyan Can you close this one

**Pull request closed without merging**
