### PR TITLE
[14.0][FIX] delivery_auto_refresh

### PR DESCRIPTION
**Pull request by solo4games**
Fix delivery_auto_refresh system parameter

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

Before this PR, enabling delivery_auto_refresh.auto_add_delivery_line and creating a SO with only service products would add shipping expenses, while standard odoo does not allow shipping expenses to be added if consumable/storable products are not present in SO

@solo4games squash commits please

**Comment by rousseldenis** [comment]
@solo4games It should be great if you add the corresponding test case. Thanks

**Review by rousseldenis — APPROVED** [review]
Makes sense.

**Comment by pedrobaeza** [comment]
Please fw-port it to upper versions:

/ocabot merge patch

**Pull request merged**
