### PR TITLE
[15.0][MIG] partner_delivery_schedule: Migration to 15.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 15.0

Please @sergio-teruel and @pedrobaeza can you review it?

@Tecnativa TT36479

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Code review

**Review by sergio-teruel — APPROVED** [review]

**Comment by rousseldenis** [comment]
@pedrobaeza @sergio-teruel @victoralmau You haven't found this ? https://github.com/OCA/stock-logistics-workflow/tree/13.0/stock_partner_delivery_window

Which is more complete (timezone management)

**Comment by pedrobaeza** [comment]
I think ours comes from 9.0. We'll check that one.

**Pull request merged**
