### PR TITLE
[15.0][MIG] carrier_deutsche_post

### PR DESCRIPTION
**Pull request by fshah-initos**
Dependent module: base_delivery_carrier_label
Pr:https://github.com/OCA/delivery-carrier/pull/476

### CODE REVIEW

**Comment by fshah-initos** [comment]
Test case and runboat/build error were not solved because the dependent module is not merged in main branch 15.0.

**Review by dsolanki-initos — COMMENTED** [review]
Code review,functional test LGTM!

**Comment by jans23** [comment]
This is not a migration but a new module. Please change the title accordingly.

**Comment by ikapasi-initos** [comment]
Hello, @hparfr it would be great if you can add reviews here.

**Comment by rousseldenis** [comment]
@fshah-initos Thanks for this. Could you follow migration guide ? 
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

Especially the Full process part as formatting changes should appear in a separate commit.

Thanks

**Comment by ikapasi-initos** [comment]
@rousseldenis, This is not migration  it is a  new module added to the delivery-carrier repository. Checks failed because the dependent module has not merged yet.

**Comment by dsolanki-initos** [comment]
The test failed because carrier_deutsche_post's dependent module base_delivery_carrier_label is not merged.
PR: https://github.com/OCA/delivery-carrier/pull/476

**Comment by pedrobaeza** [comment]
Several comments about this PR:

- The module has never landed on OCA, so it's not really a migration, but `[ADD]`. I have removed it from the migration issue.
- The name must be `delivery_deutsche_post` following the convention on other modules and started by Odoo in their enterprise repo.
- If they don't have international service (I from Spain can hire their services to delivery anything from Spain to other place in the world), this should be hosted on OCA/l10n-germany, not here.

**Comment by jans23** [comment]
Thank you for the feedback. Regarding your last point, looking at other modules in this repository such as delivery_correos_express, delivery_postlogistics, and delivery_roulier_laposte_fr I'm wondering if the same criteria applies for them too. It's fine for me to move it to OCA/l10n-germany but just want to double check that this is consistent.

**Comment by pedrobaeza** [comment]
That's the idea. For example, Correos Express operates on Spain and Portugal: https://www.correosexpress.com/web/correosexpress/servicos_incluidos. Other Spanish only carriers are on OCA/l10n-spain, like https://github.com/OCA/l10n-spain/tree/13.0/delivery_dhl_parcel or https://github.com/OCA/l10n-spain/tree/13.0/delivery_gls_asm

**Comment by jans23** [comment]
We implemented your feedback and created a PR in OCA/l10n-germany: https://github.com/OCA/l10n-germany/pull/113

**Comment by jans23** [comment]
@pedrobaeza Feel free to close this PR. (I don't have the rights to do so)

**Pull request closed without merging**
