### PR TITLE
[16.0][MIG] delivery carrier default tracking url

### PR DESCRIPTION
**Pull request by gaelTorrecillas**
Hi

Migration to 14.0 from 16.0

I change field when we add default tracking url in delivery carrier.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@gaelTorrecillas Please follow https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch

You should preserve commit history

**Comment by gaelTorrecillas** [comment]
Hello,

@rousseldenis I used this same command with origin/16.0..origin/14.0. it doesn't work?

**Review by flotho — COMMENTED** [review]
easy code review OK LGTM
Please consider the comments from @rousseldenis to finalize this.

**Comment by rousseldenis** [comment]
> Hello,
> 
> @rousseldenis I used this same command with origin/16.0..origin/14.0. it doesn't work?

That depends what origin points to and if it is up to date from OCA repo

**Comment by flotho** [comment]
much better @gaelTorrecillas , thanks for the history, waiting fro the CI

**Review by flotho — APPROVED** [review]
LGTM, code review +

**Comment by flotho** [comment]
ping @rousseldenis

**Comment by gaelTorrecillas** [comment]
hello,

I need review for this pr, where I need to change?

**Comment by flotho** [comment]
Hum @gaelTorrecillas , please re-push a commit so that the github action run a full CI, and make a rebase before
It wil ease the process

**Comment by gaelTorrecillas** [comment]
hello,

I updated my branch.

**Comment by rousseldenis** [comment]
@gaelTorrecillas I cannot reopen this as branch has changed.

**Comment by flotho** [comment]
Hi @gaelTorrecillas , could you reopen a new PR with your work

**Pull request closed without merging**
