### PR TITLE
[10.0][IMP] stock_picking_delivery_info_computation: Allow to edit/compute volume on done pickings

### PR DESCRIPTION
**Pull request by pedrobaeza**
As this information remains isolated, you have both possibilities of recomputing or manually editing the field in any state.

cc @Tecnativa

### CODE REVIEW

**Comment by rousseldenis** [comment]
> As this information remains isolated, you have both possibilities of recomputing or manually editing the field in any state.

No needs of security feature on that (to avoid losing info - without recomputing) ?

**Comment by pedrobaeza** [comment]
Well, that's something to comment apart, as this PR is not changing that. Only allowing to click or edit on any state. Any way, I don't think so, as picking are only editable by warehouse users, and both users and managers must be able to change this information IMO.

**Comment by HviorForgeFlow** [comment]
If yo are going to let users modify this field, maybe it could be tracked in chatter when is not in draft.

**Comment by pedrobaeza** [comment]
@hveficent that's also an extra feature, nothing to do with state itself. Field is not added by this module, but only put with the computation possibility. I would let it as is.

**Review by HviorForgeFlow — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
Tested functionally :+1:

**Review by victor-ditay — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@rousseldenis can we merge then?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
