### PR TITLE
[15.0][FIX] delivery_package_number: comment in code is added

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
Comment in code is added as in PR https://github.com/OCA/delivery-carrier/pull/712

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre @HaraldPanten

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@pedrobaeza probably you can merge this one too, in order to keep consistancy with V14

**Pull request merged**
