### PR TITLE
[MIG] delivery_dropoff_site : Migration to 14.0

### PR DESCRIPTION
**Pull request by BechirAouji**

### CODE REVIEW

**Review by flotho — APPROVED** [review]
Tested on ruboat with success
Code review LGTM.

Codecov seems to concern others modules like [delivery_correos_express 14.0.1.0.1]
@hildickethan-S73 , any chance to have a llok to you covering tests ?

Regarsd

**Comment by flotho** [comment]
ping @saxomanu

**Comment by saxomanu** [comment]
LGTM for me.
Just rename delivery_dropoff_site/models/procurement_group.py in stock_rule.py

Regards

**Comment by rousseldenis** [comment]
@BechirAouji Thanks for this.

Could you please follow migrating guidelines especially the Full process part ?

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Comment by hildickethan** [comment]
> Codecov seems to concern others modules like [delivery_correos_express 14.0.1.0.1] @hildickethan-S73 , any chance to have a llok to you covering tests ?

I can check it out at some point, but I believe you can merge even with that red test, especially if it doesn't concern your module.
I'd suggest renaming the commits and preserving the history to fit the migration guidelines though

**Comment by rousseldenis** [comment]
Note: coming from https://github.com/OCA/delivery-carrier/commits/10.0/delivery_dropoff_site

**Comment by rousseldenis** [comment]
@BechirAouji Could you attend comments ?

**Comment by flotho** [comment]
hi @rousseldenis I've shared the process to @BechirAouji , he will follow the guidelines for migrating from v10.0 and then apply the comments.
Basicly, a newe PR will superseed this one.

**Comment by rousseldenis** [comment]
> Basicly, a newe PR will superseed this one.

You can reuse this if you want

**Comment by flotho** [comment]
@BechirAouji , please close this one in favor of #504

**Pull request closed without merging**
