### PR TITLE
[14][MIG][WIP] delivery_carrier_deposit

### PR DESCRIPTION
**Pull request by florian-dacosta**
Need to add tests
Maybe refactore to make it more generic (like accept packages or pickings)

### CODE REVIEW

**Review by alexis-via — APPROVED** [review]

**Comment by alexis-via** [comment]
Can someone re-open this PR?

**Comment by rousseldenis** [comment]
@florian-dacosta Do you plan to fix this ?

**Comment by florian-dacosta** [comment]
Well... it would say yes. I'd like to rework, essentially on the v16 but then it will be quick to backport here the tests and eventual improvements.
I am not sure when though.. I think soon enough (unless someone do it first ofc) !

**Comment by alexis-via** [comment]
pre-commit is now green.
The failure on the odoo test is unrelated (fails in delivery_roulier)

**Comment by alexis-via** [comment]
All green !

**Pull request merged**
