### PR TITLE
[17.0][MIG] sale_order_warehouse_from_delivery_carrier: Migration to 17.0 

### PR DESCRIPTION
**Pull request by sanderlienaerts**
Changed targeted field in the `delivery.carrier` form view since the pre-migration field `amount` now resides in a `<div>` that is not always visible.

### CODE REVIEW

**Comment by sanderlienaerts** [comment]
@geomer198 thank you for creating this module, it is now migrated to 17.0. Could you please do a review?

**Review by ByteMeAsap — APPROVED** [review]
LGTM!

**Comment by ByteMeAsap** [comment]
@sanderlienaerts , can you please review the PR - https://github.com/OCA/delivery-carrier/pull/852

**Review by joepsanders — APPROVED** [review]

**Comment by sanderlienaerts** [comment]
@etobella @pedrobaeza @gurneyalex is it possible to get this one merged? thanks in advance!

**Comment by pedrobaeza** [comment]
A PSC/module maintainer should review the PR.

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
