### PR TITLE
[MIG] delivery_carrier_partner: Migration to 16.0

### PR DESCRIPTION
**Pull request by john-herholz-dt**
Simple migration to make it available in 16.0 branch. No changes

### CODE REVIEW

**Review by hbrunn — APPROVED** [review]
failing CI [unrelated](https://github.com/OCA/delivery-carrier/actions/runs/5737226172/job/15548430035?pr=683#step:8:226)

**Comment by rafaelbn** [comment]
Please @john-herholz-dt , could you please rebase this PR in order to review and review please https://github.com/OCA/delivery-carrier/pull/709 !! It is the same por 15! 😄 

Thank you!

**Comment by hbrunn** [comment]
isn't this superseded by https://github.com/OCA/delivery-carrier/pull/640?

**Comment by john-herholz-dt** [comment]
@hbrunn You are right, I didn't see this. I cancel the PR.

**Pull request closed without merging**
