### PR TITLE
12 carrier gls WIP

### PR DESCRIPTION
**Pull request by bealdav**

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Doesn't this belong to l10n-france repo?

**Comment by pedrobaeza** [comment]
Yes, we have GLS in Spain, and have specific webservice, so it's hosted in OCA/l10n-spain: https://github.com/OCA/l10n-spain/pull/1392

**Comment by bealdav** [comment]
Do you know if GLS are on the way to unify their web services or not ?

**Comment by pedrobaeza** [comment]
We talked recently with ASM Spain, and they told us that ASM was incorporated to GSM, and they are using ASM's webservices for Spain for both with no intention on changing for now.

**Comment by bealdav** [comment]
OK, thanks could you precise what is ASM and GSM ?

It's the same mess with GLS belgium it seems

**Comment by pedrobaeza** [comment]
They were 2 different companies. ASM is a local Spanish carrier that was incorporated to GLS "group".

**Comment by bealdav** [comment]
Thanks

**Pull request closed without merging**
