### PR TITLE
[WIP][12.0][ADD] Correos Express Label

### PR DESCRIPTION
**Pull request by angelmoya**
WIP

In spanish because this is a spanish carrier.

Falta por revisar el número de bultos, y contra reembolso.

### CODE REVIEW

**Comment by bealdav** [comment]
@angelmoya Thanks for this contribution.

Have you seen https://github.com/OCA/delivery-carrier/issues/192#issuecomment-493087373
Are you ok for that bring these updates in base_delivery_carrier_label ?

Do you think your module can deal with these updates ?

Thanks

**Comment by pedrobaeza** [comment]
If this is only for Spain, then maybe it's better to propose it to OCA/l10n-spain

**Comment by rousseldenis** [comment]
> If this is only for Spain, then maybe it's better to propose it to OCA/l10n-spain

España y Portugal :-)

**Comment by bealdav** [comment]
@angelmoya other topic on carriers side

Are you aware of the initiative on carriers :

https://github.com/akretion/roulier
https://github.com/akretion/roulier-gls-fr/tree/develop WIP

Carriers data process are hard to maintain, and it could help to share our works with whole python ecosystem and even more ecosystems (other languages) with python entry-points and json data (dict like)

What do you think ?

**Comment by angelmoya** [comment]
Ok, I will check

**Comment by rousseldenis** [comment]
> Ok, I will check

Maybe it could be nice to integrate the roulier lib to base_delivery_carrier_label ?

@bealdav @angelmoya Don't hesitate to create an RFC. We can talk about that as it is OCA sprint in spain now. I'm available to review an so on

**Comment by bealdav** [comment]
RFC created https://github.com/OCA/delivery-carrier/issues/197

**Comment by angelmoya** [comment]
Finally I think that will be easier to do on diferent modules, anyway before we need to check #199

**Comment by rousseldenis** [comment]
> Finally I think that will be easier to do on diferent modules, anyway before we need to check #199

Yes, move forward, let the discussion about that big change become more mature

**Comment by pedrobaeza** [comment]
Superseded by #434

**Pull request closed without merging**
