### PR TITLE
[14][MIG] delivery_roulier

### PR DESCRIPTION
**Pull request by florian-dacosta**
Standard Migration.
Base module for label generation managed with roulier lib (for now DPD France, Laposte France, Chronopost France and GLS France)
More carrier to come in the future.

Depends on https://github.com/OCA/connector-telephony/pull/239 and https://github.com/OCA/partner-contact/pull/1032

### CODE REVIEW

**Review by alexis-via — APPROVED** [review]

**Comment by rousseldenis** [comment]
@florian-dacosta Could you check tests ?

**Comment by florian-dacosta** [comment]
@rousseldenis Actually, the module depends on not yet merged modules (base_phone), that is why tests can't pass for now.

**Comment by rousseldenis** [comment]
> @rousseldenis Actually, the module depends on not yet merged modules (base_phone), that is why tests can't pass for now.

Oh, didn't see the depends. Will go there

**Comment by florian-dacosta** [comment]
@hparfr @bealdav @bguillot @rousseldenis 
PR ready to review as all dependencies are merged

**Review by hparfr — APPROVED** [review]
LGTM

**Pull request merged**
