### PR TITLE
[16.0][MIG] delivery_carrier_deposit

### PR DESCRIPTION
**Pull request by clementmbr**
rebase and fix #617

### CODE REVIEW

**Comment by clementmbr** [comment]
There are failing tests on existing modules `delivery_roulier` and `delivery_cttexpress` that I don't manage to reproduce locally

@florian-dacosta @rousseldenis @chienandalu as I don't know these other modules very well, if you have any suggestions to fix this, I'm interested! Otherwise I'll dive deeper into these modules later...

Thank you!

**Comment by rousseldenis** [comment]
@clementmbr Could you rebase ?

**Comment by clementmbr** [comment]
Hi @rousseldenis, I already did a rebase before adding my last commits and there were no new commit on 16.0 since yesterday... So my branch is already rebased and updated.

**Comment by florian-dacosta** [comment]
Hello, the `delivery_cttexpress` happens kind of randomly because direct calls are made to their api in tests (which I find extremely annoying...)
I've just fixed the issue linked to `delivery_roulier` module. Problem came from a "Fake test class" used in roulier and this module with the same name, and registry was not cleaned in this module.

Here, Odoo tests passed but not OCB, because of `delivery_cttexpress`...
@rousseldenis Is it possible when you can to re-launch the failing tests step only ?

**Review by florian-dacosta — APPROVED** [review]

**Comment by rousseldenis** [comment]
> Hello, the `delivery_cttexpress` happens kind of randomly because direct calls are made to their api in tests (which I find extremely annoying...) I've just fixed the issue linked to `delivery_roulier` module. Problem came from a "Fake test class" used in roulier and this module with the same name, and registry was not cleaned in this module.
> 
> Here, Odoo tests passed but not OCB, because of `delivery_cttexpress`... @rousseldenis Is it possible when you can to re-launch the failing tests step only ?

@florian-dacosta Done

FYI : https://github.com/OCA/odoo-community.org/pull/131

**Review by robinkeunen — APPROVED** [review]
LGTM, thx !

**Pull request merged**
