### PR TITLE
[17.0][MIG] delivery_carrier_partner: Migration to 17.0

### PR DESCRIPTION
**Pull request by salvorapi**

### CODE REVIEW

**Review by dreispt — APPROVED** [review]

**Comment by rousseldenis** [comment]
@salvorapi Thanks for this.

Next time, please follow https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#how-to

As a pre-commit commit should occurs before migration one.

**Review by rousseldenis — APPROVED** [review]

**Comment by salvorapi** [comment]
@rousseldenis oh sorry. pre-commit check on GitHub action was well and I think I don't need to run another time with a new commit. But, if it's required for merge I will do it ASAP.

Salvo

**Pull request merged**
