### PR TITLE
[14.0][MIG] delivery_carrier_multi_zip: Migration to 14.0

### PR DESCRIPTION
**Pull request by victoralmau**
Superseed: https://github.com/OCA/delivery-carrier/pull/528

Migration to 14.0

Please @pedrobaeza and @CarlosRoca13 can you review it?

@Tecnativa TT40210

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@rizzel do you agree with this one? We have preserved your commit attribution

**Comment by rizzel** [comment]
Yes, thank you 😀

**Pull request merged**
