### PR TITLE
[MIG][10.0] base_delivery_carrier_files[_document], delivery_carrier_file_tnt

### PR DESCRIPTION
**Pull request by thomaspaulb**
Replaces https://github.com/OCA/delivery-carrier/pull/184

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by thomaspaulb** [comment]
@pedrobaeza both this PR and [this one](https://github.com/OCA/delivery-carrier/pull/207) remain red, even though I have the feeling I fixed all things. Could you advise me on what I still can do to make this green?

**Comment by pedrobaeza** [comment]
There are warnings on runbot:
```
2019-07-17 12:43:10,507 6729 WARNING openerp_test odoo.addons.base_delivery_carrier_label.models.stock_pack_operation: Type conversion not implemented for product 43
2019-07-17 12:43:10,507 6729 WARNING openerp_test odoo.addons.base_delivery_carrier_label.models.stock_pack_operation: Type conversion not implemented for product 45
2019-07-17 12:43:42,286 6729 WARNING openerp_test odoo.modules.loading: module delivery_carrier_file_tnt: key 'update_xml' is deprecated in favor of 'data' for file 'carrier_file_view.xml'.
```

**Comment by rousseldenis** [comment]
@thomaspaulb Do you plan to finish this ?

**Comment by thomaspaulb** [comment]
@rousseldenis I think it's now finished.

**Review by MPoch-PlanetaTIC — APPROVED** [review]
I have reviewed the code and tested this module. Everything is ok.

**Comment by thomaspaulb** [comment]
@gjotten How about a functional review here? We've been using this one a long time and its 12.0 port is about to get merged also.

**Comment by thomaspaulb** [comment]
@rousseldenis Could you be the merging angel here

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
