### PR TITLE
7.0 pylint

### PR DESCRIPTION
**Pull request by yvaucher**
Superseeds #36

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Two minor flake8 issues:

```
./delivery_carrier_label_postlogistics/postlogistics/web_service.py:251:24: E128 continuation line under-indented for visual indent
./delivery_carrier_label_postlogistics/res_config.py:107:20: E124 closing bracket does not match visual indentation
```

**Comment by pedrobaeza** [comment]
:+1:

**Comment by tafaRU** [comment]
:+1:

**Comment by bwrsandman** [comment]
:+1:

**Pull request merged**
