### PR TITLE
[14.0] [FIX] delivery_auto_refresh: manually delete delivery line

### PR DESCRIPTION
**Pull request by renda-dev**
supersedes https://github.com/OCA/delivery-carrier/pull/780 for version 14.0

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

@santostelmo what do you think?

**Comment by francesco-ooops** [comment]
Also @pedrobaeza as module author :)

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM

**Comment by pedrobaeza** [comment]
I don't think the delivery line should be deleted, as it will be later added (even in core) when the picking is validated. It should be nullified putting 100% discount or price 0.

**Comment by francesco-ooops** [comment]
@pedrobaeza am I missing something? (vanilla odoo)

https://www.loom.com/share/54f81dbe2ef24062b7c07ae0a216b58d?sid=198083b2-f6eb-40a9-955f-20ada0d03df5

To be clear, this is what we're trying to solve: https://github.com/OCA/delivery-carrier/pull/780#issue-2181169861

**Review by pedrobaeza — APPROVED** [review]
You are probably using estimated costs instead of real costs, or the delivery cost in the picking is 0, but as said, there are occasions where standard re-adds the line. Anyway, the issue should be solved indeed.

/ocabot merge patch

**Pull request merged**
