### PR TITLE
[13.0][ADD] delivery_postlogistics_server_env

### PR DESCRIPTION
**Pull request by TDu**
Adds OCA Server Environment features to Delivery Postlogistics.

The module delivery_postlogistics is in this PR:

* https://github.com/OCA/delivery-carrier/pull/323

### CODE REVIEW

**Comment by guewen** [comment]
In travis: `Unmet dependencies: delivery_postlogistics, server_environment`
For the first one, we need https://github.com/OCA/delivery-carrier/pull/323, but for the second one, should you add `server-env` in the oca_requirements file?

**Comment by TDu** [comment]
Done for `server-env`

**Comment by mmequignon** [comment]
LGTM, however, I think you should rebase on #323 in order to fix travis and make this PR mergeable

**Comment by TDu** [comment]
Rebased on the included PR #323

**Review by mmequignon — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Review by simahawk — CHANGES_REQUESTED** [review]
blocking it till #323 is done

**Comment by simahawk** [comment]
#323 is getting merged

**Comment by sebalix** [comment]
@simahawk Travis is green, but this would need a rebase to get runbot green as well
EDIT: rebased, all green

**Review by simahawk — APPROVED** [review]

**Pull request merged**
