### PR TITLE
[16.0][IMP] delivery_package_number: port missing commits from 15

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa 

Commits from v15:

- [x]  [IMP] delivery_package_number: Make compatible with multi pickings validatio(9e52f0964c5f6f0fde08e79bb5a9a543347c7908)
- [x] [IMP] delivery_package_number: Ask only once for the number of packages wizard. (e3b3f87bd26b4ec9a3bf388beefa9759a6a596fc)
- [x] [FIX] delivery_package_number: download label (c3e3262bb1f8e4e3936e45be4475d9fc558eb6fe)

Better port required in PR https://github.com/OCA/delivery-carrier/pull/788

ping @CarlosRoca13 @carlos-lopez-tecnativa

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
What about this issue? https://github.com/OCA/delivery-carrier/pull/795

**Comment by pedrobaeza** [comment]
Please include #795

**Comment by sergio-teruel** [comment]
New commit added!! (https://github.com/OCA/delivery-carrier/pull/795)

**Review by chienandalu — APPROVED** [review]
:+1:

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

Please fw-port it to 17

**Pull request merged**
