### PR TITLE
[16.0][MIG] delivery_carrier_partner

### PR DESCRIPTION
**Pull request by glitchov**
Straight migration from 14.0.
The module adds a partner_id on delivery.carrier which corresponds to the partner handling the shipping.

### CODE REVIEW

**Review by bealdav — APPROVED** [review]
LGTM

**Review by OscarIndias — APPROVED** [review]
LGTM!

**Comment by francesco-ooops** [comment]
@rousseldenis what is this? https://github.com/OCA/delivery-carrier/pull/640/files#diff-dae45fc96102be8a4766f1719ce10c6561f4e49707dfec412dad7c058909252b

**Pull request merged**
