### PR TITLE
[14][ADD] delivery_schenker_quant_package_dimension: Length Width Height

### PR DESCRIPTION
**Pull request by mt-software-de**
I extracted the volume extension from delivery_schenker into an own addon
and added as well the missing fields for Length Width and Height. 

cc @chienandalu @jbaudoux

### CODE REVIEW

**Review by jbaudoux — APPROVED** [review]

**Comment by mt-software-de** [comment]
@chienandalu, @raumschmiede-joshuaL maybe you can give this one a review?

**Review by chienandalu — COMMENTED** [review]
Hi @mt-software-de 

We don't maintain this module at the moment, so maybe I'm not the right one to review this one.

**Comment by mt-software-de** [comment]
> Hi @mt-software-de 
> 
> We don't maintain this module at the moment, so maybe I'm not the right one to review this one.

Oh yes my fault.

**Comment by mt-software-de** [comment]
Maybe @hildickethan-S73 ?

**Review by hildickethan — APPROVED** [review]
Looks good

**Review by raumschmiede-joshuaL — APPROVED** [review]

**Comment by mt-software-de** [comment]
@jbaudoux could you merge this one?

**Pull request merged**
