### PR TITLE
[MIG] delivery_multi_destination: Migration to 16.0

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Comment by victoralmau** [comment]
Please, cherry-pick https://github.com/OCA/delivery-carrier/pull/636 to commit history

**Comment by pedrobaeza** [comment]
Another round of patches you should include: #653 #650

**Comment by pedrobaeza** [comment]
@GabbasovDinar can you cherry-pick latest commits to complete this and merge it if everything OK?

**Comment by jado95** [comment]
Hi @GabbasovDinar  and thanks for PR.
Maybe there is problem on `name_search` method.
If i write word on field carrier_id on picking, table isn't filtered for word that i insert.
Does it work for you?

**Comment by GabbasovDinar** [comment]
Hello @pedrobaeza 

I apologize for the delay on this PR, I've moved all the remaining commits over

**Comment by pedrobaeza** [comment]
Please check CI.

**Comment by carolinafernandez-tecnativa** [comment]
Hi, could you please rebase? i have checked on my local your changes and works correctly.

**Comment by rousseldenis** [comment]
@GabbasovDinar Do you mind if we switch to #766 ?

**Pull request closed without merging**
