### PR TITLE
[13.0][FIX] delivery_tnt_oca: Set correct Sender (warehouse or company address).

### PR DESCRIPTION
**Pull request by victoralmau**
Set correct Sender (warehouse or company address).

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT39666

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
:+1: Out of curiosity: shouldn't this be outside the connector logic?

**Comment by victoralmau** [comment]
> +1 Out of curiosity: shouldn't this be outside the connector logic?

Perhaps a connector base module with carriers with some logics would avoid applying the same changes to all carrier modules, but it would be a rather hard dependency that is not expressly necessary.

**Comment by chienandalu** [comment]
> Perhaps a connector base module with carriers with some logics would avoid applying the same changes to all carrier modules

Well, I meant that this Odoo stuff should go in the delivery.carrier methods. The connector class (specific to each API) should be as thin as possible IMO. Anyway, not important right now

**Pull request merged**
