### PR TITLE
[18.0] [MIG] delivery_carrier_partner

### PR DESCRIPTION
**Pull request by Borruso**
migration from 17.0 to 18.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Comment by salvorapi** [comment]
Hi @Borruso ,

good work! I think that you just need to add a simple test case and it's done. 👍 💯

**Review by salvorapi — APPROVED** [review]
LGTM

**Comment by christian-ramos-tecnativa** [comment]
Thanks for your contribution! Can you squash the test commit into the Migration one?

**Comment by Borruso** [comment]
> Thanks for your contribution! Can you squash the test commit into the Migration one?

Can you check?

**Review by christian-ramos-tecnativa — APPROVED** [review]
LGTM

**Review by sebalix — APPROVED** [review]

**Pull request merged**
