### PR TITLE
[16.0][FIX] delivery_package_number: Don't reset number on backorder

### PR DESCRIPTION
**Pull request by pedrobaeza**
Forward-port of #696 

@Tecnativa

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Functionally tested in local environment. LGTM.

**Review by angelgarciadelachica — APPROVED** [review]
Reviewed in local and it works correctly. 
On the other hand, as in the PR https://github.com/OCA/delivery-carrier/pull/696, it does not work in the runbot.

**Comment by sbidoul** [comment]
You can see in this [log](https://runboat.odoo-community.org/api/v1/builds/b84e3c687-289a-4add-b0f9-d24713bb6463/init-log) that the correct commit is obtained from github (look for the curl command at the beginning).

I have looked in the pod and the correct code has been downloaded. So the fault is not with runboat. There must be something else going on.

**Comment by HaraldPanten** [comment]
Thanks @sbidoul ! Then, probably a "test evasive" use case is creating inconsistance.

**Comment by pedrobaeza** [comment]
Very weird indeed. Let's merge it anyway for finishing the fw-port chain:

/ocabot merge patch

**Pull request merged**
