### PR TITLE
[13.0][MIG] delivery_carrier_partner

### PR DESCRIPTION
**Pull request by acsonefho**
Migration of the module `delivery_carrier_partner`.

### CODE REVIEW

**Comment by acsonefho** [comment]
@ThomasBinsfeld @rousseldenis Can you review please? :)

**Comment by rousseldenis** [comment]
@acsonefho Did you follow https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#howto to migrate ? Why removing .pot and translations? pre-commit changes should appear in a separate commit.

**Comment by acsonefho** [comment]
> @acsonefho Did you follow https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#howto to migrate ? Why removing .pot and translations? pre-commit changes should appear in a separate commit.

I follow the guideline and I accidentally removed translations files! (I'm going to restore them).
About pre-commit, there are only 3 changes (as this module is very small) so I did only 1 commit.

**Review by ThomasBinsfeld — APPROVED** [review]

**Comment by rousseldenis** [comment]
> > @acsonefho Did you follow https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#howto to migrate ? Why removing .pot and translations? pre-commit changes should appear in a separate commit.
> 
> I follow the guideline and I accidentally removed translations files! (I'm going to restore them).
> About pre-commit, there are only 3 changes (as this module is very small) so I did only 1 commit.

Ok. In guidelines, we'd prefer putting pre-commit changes in a separate commit before migration one in order to get real migration changes in the good commit. And it's easier to review. But don't worry, it's ok for this

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by gaikaz — APPROVED** [review]
Code LGTM

**Comment by rousseldenis** [comment]
@acsonefho Ok, let's go here. For the next time, don't forget to follow OCA guidelines and put black modifications into a separated commit (before the migration one).

**Pull request merged**
