### PR TITLE
[10] delivery  carrier b2c

### PR DESCRIPTION
**Pull request by EBII**

### CODE REVIEW

**Comment by bealdav** [comment]
@EBII Please, could you add this in readme please

This module adds specific fields to partner for delivery purposes. Some carrier services offer to deliver packages to any place in a country (e.g. 'So Colissimo' in France). In this case addition fields are required with a more complete view on partner

**Comment by bealdav** [comment]
:+1:

**Comment by bealdav** [comment]
Ok for me, but 1 commit could have been sufficient here, may be in squash / merge

**Comment by hparfr** [comment]
👍

**Review by yvaucher — APPROVED** [review]

**Comment by mourad-ehm** [comment]
Code review :+1:

**Comment by yvaucher** [comment]
@mourad-ehm this was merged one week ago :wink:

**Pull request merged**
