### PR TITLE
[13.0][MIG] stock_picking_report_delivery_cost: Migration to 13.0

### PR DESCRIPTION
**Pull request by victoralmau**
@Tecnativa TT25954

### CODE REVIEW

**Review by joao-p-marques — COMMENTED** [review]
Code LGTM.

However, I can't test this functionally. When I follow the instructions and generate the report, I don't see the Delivery Cost. Is there some step missing from the instructions?

**Comment by pedrobaeza** [comment]
@joao-p-marques you need to set a delivery method with cost in the sale, let it propagate it to picking, and then print the report.

**Comment by joao-p-marques** [comment]
Thank you @pedrobaeza 
Functional review ok :+1:

**Comment by pedrobaeza** [comment]
Please put the explicit approval then

**Review by joao-p-marques — APPROVED** [review]

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :+1:

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please update POT + Spanish translation

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
