### PR TITLE
[14.0][MIG] delivery_auto_refresh: Migration to 14.0

### PR DESCRIPTION
**Pull request by simahawk**
Replaces #439.
In addition to it:
1. include fix from #440
2. speed up tests w/ setUpClass + no tracking
3. unify lookup of params and use the right converter for boolean strings

### CODE REVIEW

**Comment by simahawk** [comment]
tests failure seems unrelated. I'll get back to them when possible.

```
FAIL: TestRoutePutaway.test_wizard_send_shipping
Traceback (most recent call last):
  File "/home/travis/build/OCA/delivery-carrier/setup/delivery_carrier_pricelist/odoo/addons/delivery_carrier_pricelist/tests/test_delivery_pricelist.py", line 103, in test_wizard_send_shipping
    self.assertEqual(result, [{"exact_price": 0.0, "tracking_number": False}])
AssertionError: Lists differ: [{'exact_price': 10.0, 'tracking_number': False}] != [{'exact_price': 0.0, 'tracking_number': False}]
First differing element 0:
{'exact_price': 10.0, 'tracking_number': False}
{'exact_price': 0.0, 'tracking_number': False}
- [{'exact_price': 10.0, 'tracking_number': False}]
?                  -
+ [{'exact_price': 0.0, 'tracking_number': False}]
 
Module delivery_carrier_pricelist: 1 failures, 0 errors of 4 tests
FAIL: TestDeliveryMultiDestination.test_delivery_multi_destination
Traceback (most recent call last):
  File "/home/travis/build/OCA/delivery-carrier/setup/delivery_multi_destination/odoo/addons/delivery_multi_destination/tests/test_delivery_multi_destination.py", line 161, in test_delivery_multi_destination
    self.assertAlmostEqual(sale_order_line.price_unit, 50, 2)
AssertionError: 10.0 != 50 within 2 places
 
FAIL: TestDeliveryMultiDestination.test_picking_validation
Traceback (most recent call last):
  File "/home/travis/build/OCA/delivery-carrier/setup/delivery_multi_destination/odoo/addons/delivery_multi_destination/tests/test_delivery_multi_destination.py", line 203, in test_picking_validation
    self.assertEqual(picking.carrier_id, self.carrier_multi)
AssertionError: delivery.carrier(3,) != delivery.carrier(12,)
```

**Comment by chienandalu** [comment]
Can you add: https://github.com/OCA/delivery-carrier/pull/469

**Comment by elvise** [comment]
hi @simahawk any chance for this PR ?

**Comment by francesco-ooops** [comment]
@simahawk porting was finished in PR #472 , could you review? 

thanks!

**Pull request closed without merging**
