### PR TITLE
Update __manifest__.py

### PR DESCRIPTION
**Pull request by andreampiovesana**
"application": False

### CODE REVIEW

**Comment by andreampiovesana** [comment]
is really an app?

**Comment by rousseldenis** [comment]
@jbaudoux @jcoux @yvaucher

**Comment by andreampiovesana** [comment]
@rousseldenis can you fix?

**Review by jbaudoux — CHANGES_REQUESTED** [review]
All delivery_* connector modules in enterprise are `application=True`

So this is consistent and there is no reason to change that

**Comment by andreampiovesana** [comment]
change all

Il giorno lun 5 feb 2024 alle ore 09:31 Jacques-Etienne Baudoux <
***@***.***> ha scritto:

**Pull request closed without merging**
